### ISSUE TITLE
"Failed to compile" error message in the new generated app

### ISSUE THREAD

**Issue by krzyjel** [codeandpepper/janush#242]
Type: Bug
Operating system: MacOS 10.15.7
Affects Version: 1.0.3
Priority: High
Severity: Critical
Preconditions: Generate the new application using `janush` command

**Steps to reproduce:**
1. Use command `cd web`
2. Use command `npm run start` or `yarn start`

**Actual result:** 
After initial response there is an error message in terminal: 
`"Failed to compile. 
'Router' cannot be used as a JSX component.
  Its instance type 'BrowserRouter' is not a valid JSX element".`
App is opening in default browser with index page of Janush, but no action can be performed on it.

**Expected result:**
The command finished running application correctly.
In default browser window is opening with index page of Janush and you can perform some action on it (for example can click sign in on the page and it will redirect to the sign in page).

**Attachments:**
<img width="1147" alt="image 10 17 01" src="https://user-images.githubusercontent.com/106099542/171607428-90a59124-9872-451b-879c-cb37bab71feb.png">

**Comment by hadrysm** [comment]
The problem here is the wrong node version. You had node version 14 set and Janush has dependencies in package-lock.json for node v16.

## Solution:
Reinstall the application from **node v16**
