### ISSUE TITLE
Change the flow with reset password procedure or fix the issue with email templates

### ISSUE THREAD

**Issue by arkjel** [codeandpepper/janush#256]
There is some issue in the app. When we fill the `reset password` form we should send the email template with the `reset password link` but it doesn't work now and the user is getting only the verification code to reset they password. 

**We have two options:**
- fix the bug with email templates
- change the flow and show the user verification code screen and then when the user fill the form we can redirect him to the reset password form with two new inputs (password & confirm password with validation)

**Current screen when the user fill the `Reset password` form:**
![image](https://user-images.githubusercontent.com/13696203/172788033-809fa7ad-a7a5-4550-b106-33440366666d.png)

**The screen after `sign up` process which can be adjust to the new reset password flow:**

![image](https://user-images.githubusercontent.com/13696203/172787562-58211eac-aee4-4509-885d-7acdc8e4ecb4.png)

After that we should show the screen with two inputs fields (password & confirm password) with validation. At the end of the flow the user should be redirected to the `sign in` page

**Comment by MastalerzKamil** [comment]
The proposed screen seems a better solution however the problem can be many requests for resend email from bots or impatient users so there should be an extra timer for resend email
