### ISSUE TITLE
Error information after running command "npm run cdk bootstrap"

### ISSUE THREAD

**Issue by krzyjel** [codeandpepper/janush#269]
After running command `npm run cdk bootstrap` I get error information. 
I have version 1.0.9 of janush package.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/106099542/174289600-64830233-9062-43b1-886c-fb9efba10d08.png">

**Comment by MastalerzKamil** [comment]
Problem has been solved by using SSO instead of AWS root account connected to organization
